version: '3.8'

services:
  personal-kb:
    build: .
    container_name: personal-kb
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - REPL_ID=${REPL_ID}
      - REPLIT_DOMAINS=${REPLIT_DOMAINS}
      - ISSUER_URL=${ISSUER_URL:-https://replit.com/oidc}
      - BACKUP_DIR=/app/backups
    volumes:
      - uploads:/app/uploads
      - backups:/app/backups
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: personal-kb-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-personalkb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  uploads:
  backups: