-- Sample entries for testing Personal KB
-- This will be executed via the API to create realistic test data

-- Journal Entries
INSERT INTO entries (user_id, title, content, type, date) VALUES
('43162797', 'Monday Morning Reflections', 'Started the week with a long walk in the park. The autumn leaves are beginning to change color, creating a beautiful tapestry of reds and golds. I''ve been thinking about the upcoming project deadlines and how to better manage my time. There''s something peaceful about the early morning hours when the world is still quiet. #productivity #nature #reflection', 'journal', '2024-10-15'),
('43162797', 'Weekend Adventures', 'Spent Saturday exploring the farmer''s market downtown. Found some incredible heirloom tomatoes and had a great conversation with the vendor about sustainable farming practices. Later visited the art museum''s new contemporary exhibit. The interactive installations were thought-provoking. #weekends #art #local', 'journal', '2024-10-12'),
('43162797', 'Technology Thoughts', 'Been reading about the latest developments in AI and machine learning. It''s fascinating how rapidly the field is evolving. The potential applications seem endless, but I''m also mindful of the ethical considerations. Need to dive deeper into the research papers. #technology #ai #learning', 'journal', '2024-10-08'),
('43162797', 'Cooking Experiment', 'Tried making homemade pasta from scratch today. The process was more involved than expected, but incredibly satisfying. The texture was perfect, and paired beautifully with the simple tomato sauce. Definitely want to experiment more with Italian cuisine. #cooking #food #italian', 'journal', '2024-10-05'),
('43162797', 'Book Club Discussion', 'Had an engaging discussion about "The Seven Husbands of Evelyn Hugo" at book club tonight. Everyone had different interpretations of the characters'' motivations. Sarah brought up some excellent points about unreliable narrators. Looking forward to next month''s selection. #books #discussion #friends', 'journal', '2024-10-02');

-- Quick Notes
INSERT INTO entries (user_id, title, content, type, date) VALUES
('43162797', 'Meeting Notes - Q4 Planning', 'Key decisions from today''s planning meeting:\n- Budget increase for marketing campaigns\n- New hire for the design team by November\n- Focus on mobile optimization\n- Quarterly review scheduled for December 15th\n\nAction items: Follow up with HR about job posting, review mobile analytics', 'note', '2024-10-16'),
('43162797', 'Gift Ideas', 'Birthday gift ideas for Mom:\n- That ceramic workshop she mentioned\n- New gardening gloves and tools\n- Subscription to her favorite magazine\n- Weekend trip to the coast\n\nNeed to decide by next week!', 'note', '2024-10-14'),
('43162797', 'Research Topics', 'Topics to explore for the sustainability project:\n- Carbon footprint tracking methods\n- Renewable energy adoption rates\n- Waste reduction strategies in offices\n- Employee engagement in green initiatives\n\nStart with the carbon footprint analysis', 'note', '2024-10-11'),
('43162797', 'Travel Checklist', 'Things to remember for the business trip:\n- Print boarding passes\n- Pack phone charger\n- Bring presentation materials\n- Confirm hotel reservation\n- Check weather forecast\n- Download offline maps', 'note', '2024-10-09'),
('43162797', 'Recipe Ideas', 'New recipes to try this month:\n- Thai green curry with vegetables\n- Sourdough bread (finally!)\n- Chocolate chip cookies from scratch\n- Mushroom risotto\n- Greek lemon soup\n\nStart with the curry this weekend', 'note', '2024-10-07');

-- People
INSERT INTO entries (user_id, title, content, type, date, name, email, phone, address, date_of_birth, company, position, notes) VALUES
('43162797', 'Dr. Sarah Martinez', 'Met Sarah at the medical conference last month. She''s doing groundbreaking research in neurology and has been incredibly helpful in understanding the latest treatment protocols. Very knowledgeable about brain imaging techniques. We discussed potential collaboration opportunities.', 'person', '2024-10-16', 'Dr. Sarah Martinez', 'sarah.martinez@medical.edu', '(555) 123-4567', '1200 University Ave, Medical Center', '1985-03-15', 'University Medical Center', 'Research Neurologist', 'Specializes in brain imaging, interested in collaboration'),
('43162797', 'Marcus Thompson', 'Marcus is our lead developer who joined the team six months ago. Exceptional skills in full-stack development, particularly strong with React and Node.js. Always willing to help others and has great problem-solving abilities. Organized the recent team hackathon.', 'person', '2024-10-15', 'Marcus Thompson', 'marcus.t@company.com', '(555) 234-5678', '456 Tech Street, Downtown', '1990-08-22', 'TechCorp Solutions', 'Senior Developer', 'Full-stack expert, great mentor, hackathon organizer'),
('43162797', 'Elena Rodriguez', 'Elena runs the local coffee shop where I work most mornings. She''s been in business for over 10 years and has built an amazing community hub. Her espresso is the best in the city, and she remembers everyone''s order. Very passionate about supporting local artists.', 'person', '2024-10-13', 'Elena Rodriguez', 'elena@coffeelife.com', '(555) 345-6789', '789 Main Street, Coffee District', '1978-11-30', 'Coffee Life Café', 'Owner', 'Amazing coffee, supports local artists, community builder'),
('43162797', 'Prof. David Chen', 'My former professor who now works as a consultant. David has incredible insights into market analysis and strategic planning. He''s published several papers on consumer behavior and is always up for discussing new business concepts over dinner.', 'person', '2024-10-10', 'Prof. David Chen', 'dchen@business.edu', '(555) 456-7890', '321 Academic Way, University District', '1972-06-12', 'Business Consulting Group', 'Senior Consultant', 'Market analysis expert, published researcher, great mentor'),
('43162797', 'Lisa Park', 'Lisa is my neighbor and an excellent graphic designer. She freelances for various tech companies and has a great eye for user interface design. Recently helped me with some design questions for a side project. Very creative and always experimenting with new tools.', 'person', '2024-10-08', 'Lisa Park', 'lisa.park.design@gmail.com', '(555) 567-8901', '654 Residential Lane, Suburb', '1988-01-18', 'Freelance', 'Graphic Designer', 'UI/UX specialist, creative, helpful neighbor');

-- Places
INSERT INTO entries (user_id, title, content, type, date, address, website, phone, hours, notes) VALUES
('43162797', 'Central Library', 'The main branch of our city library system. Incredible architecture with high ceilings and natural light flooding through large windows. The third floor has the best quiet study spaces, and they have an excellent collection of design and technology books. Free wifi and plenty of power outlets.', 'place', '2024-10-16', '100 Library Avenue, Downtown', 'www.citylibrary.org', '(555) 111-2222', 'Mon-Thu: 9am-9pm, Fri-Sat: 9am-6pm, Sun: 1pm-5pm', 'Third floor best for studying, excellent design book collection'),
('43162797', 'Mountain View Trail', 'A 3-mile hiking trail that offers stunning views of the valley below. The trail is well-maintained with clear markers every quarter mile. Best visited in the early morning when it''s cooler and wildlife is more active. The viewpoint at the summit has benches and a small shelter.', 'place', '2024-10-14', 'Trail Head: 500 Forest Road, Mountain Park', 'www.mountainpark.gov', '(555) 222-3333', 'Dawn to Dusk', '3-mile trail, best in early morning, summit viewpoint has shelter'),
('43162797', 'Artisan Bakery', 'Small family-owned bakery that makes the most incredible sourdough bread. They use traditional techniques and source flour from local farms. The croissants are flaky perfection, and their seasonal fruit tarts are outstanding. Limited seating but worth the wait.', 'place', '2024-10-12', '234 Baker Street, Historic District', 'www.artisanbakery.com', '(555) 333-4444', 'Tue-Sun: 7am-3pm, Closed Mondays', 'Amazing sourdough, traditional techniques, seasonal specialties'),
('43162797', 'Innovation Hub', 'A co-working space and startup incubator downtown. Modern facilities with flexible workspace options, meeting rooms, and event spaces. Regular networking events and workshops. The community is very collaborative and supportive. Great coffee bar on the second floor.', 'place', '2024-10-10', '888 Innovation Drive, Business District', 'www.innovationhub.co', '(555) 444-5555', '24/7 for members, Office hours: Mon-Fri 8am-6pm', 'Co-working space, networking events, collaborative community'),
('43162797', 'Sunset Beach', 'A peaceful stretch of coastline perfect for evening walks and watching the sunset. Less crowded than the main beaches, with tide pools to explore at low tide. The nearby parking is free, and there are picnic tables available. Great spot for reflection and photography.', 'place', '2024-10-08', 'Coastal Highway Mile Marker 15', 'www.coastalparks.gov', '(555) 555-6666', 'Sunrise to Sunset', 'Peaceful, tide pools, free parking, great for sunset photography');

-- Things
INSERT INTO entries (user_id, title, content, type, date, category, brand, model, purchase_date, warranty_info, manual_link, notes) VALUES
('43162797', 'Standing Desk', 'Electric height-adjustable desk that has transformed my work setup. Smooth transition between sitting and standing positions with memory presets. The desktop is spacious enough for dual monitors and has built-in cable management. Significantly improved my posture and energy levels during long work sessions.', 'thing', '2024-10-16', 'Office Furniture', 'ErgoDesk Pro', 'ED-2000', '2024-09-15', '5-year warranty, expires 2029-09-15', 'www.ergodesk.com/manuals/ed2000', 'Memory presets: sitting 28", standing 42", great cable management'),
('43162797', 'Coffee Grinder', 'Burr grinder that produces consistently sized grounds for perfect coffee extraction. Much quieter than my previous blade grinder and the results are noticeably better. Easy to clean and adjust for different brewing methods. Essential tool for my morning coffee routine.', 'thing', '2024-10-14', 'Kitchen Appliances', 'BrewMaster', 'BM-500', '2024-08-20', '2-year warranty, expires 2026-08-20', 'www.brewmaster.com/support/bm500', 'Burr grinder, quiet operation, adjustable grind size'),
('43162797', 'Wireless Headphones', 'Excellent noise-canceling headphones perfect for both work calls and music. Battery life easily lasts a full day, and the quick charge feature is incredibly convenient. Comfortable for extended wear and the sound quality is exceptional across all frequencies.', 'thing', '2024-10-12', 'Electronics', 'SoundMax', 'SM-NC300', '2024-07-10', '1-year warranty, expires 2025-07-10', 'www.soundmax.com/manuals/nc300', 'Noise-canceling, 24-hour battery, quick charge feature'),
('43162797', 'Mechanical Keyboard', 'Tactile switches provide excellent typing feedback without being too loud for the office. The build quality is solid with a metal frame, and the key layout is perfect for programming. RGB lighting can be customized but I usually keep it minimal.', 'thing', '2024-10-10', 'Computer Accessories', 'TypeCraft', 'TC-87', '2024-06-05', '2-year warranty, expires 2026-06-05', 'www.typecraft.com/support/tc87', 'Tactile switches, metal frame, customizable RGB, great for programming'),
('43162797', 'Plant Humidifier', 'Small ultrasonic humidifier specifically for maintaining optimal humidity around my houseplants. Quiet operation and the mist output is adjustable. Has made a noticeable difference in plant health, especially during dry winter months. Easy to refill and clean.', 'thing', '2024-10-08', 'Home & Garden', 'PlantCare', 'PC-200', '2024-05-15', '1-year warranty, expires 2025-05-15', 'www.plantcare.com/manuals/pc200', 'Ultrasonic, adjustable mist, quiet operation, great for plant health');