name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        target: default
        arch: x86_64
        
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Initialize Capacitor (if needed)
      run: |
        if [ ! -d "android" ]; then
          npx cap add android
        fi
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Verify Java version
      run: |
        java -version
        javac -version
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Build Android APK
      run: |
        cd android
        ./gradlew clean --no-daemon --stacktrace
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: personal-kb-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Android AAB (Release)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        cd android
        ./gradlew bundleRelease
        
    - name: Upload AAB
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: personal-kb-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab